### ISSUE TITLE
Python 3.9 Build Error

### ISSUE THREAD

**Issue by ax3l** [ornladios/ADIOS#216]
Building against CPython 3.9 I see the following errors:
```
/home/conda/feedstock_root/build_artifacts/adios-python_1602593380049/_build_env/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
adios.cpp: In function 'PyObject* PyInit_adios()':
adios.cpp:52250:30: error: 'PyTypeObject {aka struct _typeobject}' has no member named 'tp_print'; did you mean 'tp_dict'?
   __pyx_type_5adios_softdict.tp_print = 0;
                              ^~~~~~~~
                              tp_dict
```

Refs.: https://github.com/conda-forge/adios-python-feedstock

**Comment by ax3l** [comment]
Ping @jychoi-hpc: do you think this can be easily fixed?

**Comment by jychoi-hpc** [comment]
@ax3l sorry for my late reply. Can you help me to understand the error? Is this because of using new version of numpy? which python version did you use? I tried to build on Cori with python 3.9 (numpy 1.20.3, cython 0.29.24) and did get an error.

**Comment by ax3l** [comment]
@jychoi-hpc no worries. I think this is due to a new version of CPython. `tp_print` is dropped from Python 3.9 onwards.
https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_vectorcall_offset

Maybe Cython of some of the ADIOS Cython calls need to be updated?

**Comment by ax3l** [comment]
I see the problem on conda-forge:
  https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_vectorcall_offset
and build like this:
  https://github.com/conda-forge/adios-python-feedstock/blob/master/recipe/build.sh

Should I run Cython or something beforehand? :)

**Comment by jychoi-hpc** [comment]
I just tried again by doing exactly the same thing in `build.sh` on Cori without any issue. I used Python 3.9.7. It looks condo-forge is using more recent python. Do you know which version of python on conda-forge is used?

Alternatively, you can try the following command to invoke 'cython' beforehand:
```
make CYTHON=y python
```
instead of 
```
make python
```

**Comment by ax3l** [comment]
Thanks a lot, let's try this in Spack (https://github.com/spack/spack/pull/28003) and Conda-Forge (https://github.com/conda-forge/adios-python-feedstock/pull/11).

X-ref: #202

**Comment by ax3l** [comment]
I tried this in Spack (...) with Python 3.9.9 and still get the following errors:
```
==> Installing py-adios-1.13.1-a6rwa4ie27dw6mhrg3pkklwhmv3lpiyl
==> No binary for py-adios-1.13.1-a6rwa4ie27dw6mhrg3pkklwhmv3lpiyl found: installing from source
==> Using cached archive: /home/axel/src/spack/var/spack/cache/_source-cache/archive/b1/b1c6949918f5e69f701cabfe5987c0b286793f1057d4690f04747852544e157b.tar.gz
==> No patches needed for py-adios
==> py-adios: Executing phase: 'build_clib'
==> py-adios: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    '/home/axel/src/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.3.0/python-3.9.9-s776hol6xrbzt5key3hfwecl4mowuupv/bin/python3.9' '-s' 'setup_mpi.py' '--no-user-cfg' 'install' '--prefix=/home/axel/src/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.3.0/py-adios-1.13.1-a6rwa4ie27dw6mhrg3pkklwhmv3lpiyl' '--root=/home/axel/src/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.3.0/py-adios-1.13.1-a6rwa4ie27dw6mhrg3pkklwhmv3lpiyl' '--install-purelib=lib/python3.9/site-packages' '--install-platlib=lib/python3.9/site-packages' '--install-scripts=bin' '--install-data=' '--install-headers=include/python3.9'

11 errors found in build log:
     34                      from /home/axel/src/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.3.
            0/py-numpy-1.22.0-aw74hafw4uqvqhaixfj762syb42cwi5s/lib/python3.9/site-packages/numpy/cor
            e/include/numpy/arrayobject.h:5,
     35                      from adios_mpi.cpp:541:
     36     /home/axel/src/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.3.0/py-numpy-1.22.0-aw74
            hafw4uqvqhaixfj762syb42cwi5s/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_
            7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with 
            " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     37        17 | #warning "Using deprecated NumPy API, disable it with " \
     38           |  ^~~~~~~
     39     adios_mpi.cpp: In function 'PyObject* PyInit_adios_mpi()':
  >> 40     adios_mpi.cpp:52761:34: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member n
            amed 'tp_print'
     41     52761 |   __pyx_type_9adios_mpi_softdict.tp_print = 0;
     42           |                                  ^~~~~~~~
  >> 43     adios_mpi.cpp:52772:30: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member n
            amed 'tp_print'
     44     52772 |   __pyx_type_9adios_mpi_file.tp_print = 0;
     45           |                              ^~~~~~~~
  >> 46     adios_mpi.cpp:52798:35: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member n
            amed 'tp_print'
     47     52798 |   __pyx_type_9adios_mpi_blockinfo.tp_print = 0;
     48           |                                   ^~~~~~~~
  >> 49     adios_mpi.cpp:52811:29: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member n
            amed 'tp_print'
     50     52811 |   __pyx_type_9adios_mpi_var.tp_print = 0;
     51           |                             ^~~~~~~~
  >> 52     adios_mpi.cpp:52817:30: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member n
            amed 'tp_print'
     53     52817 |   __pyx_type_9adios_mpi_attr.tp_print = 0;
     54           |                              ^~~~~~~~
  >> 55     adios_mpi.cpp:52823:31: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member n
            amed 'tp_print'
     56     52823 |   __pyx_type_9adios_mpi_group.tp_print = 0;
     57           |                               ^~~~~~~~
  >> 58     adios_mpi.cpp:52849:35: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member n
            amed 'tp_print'
     59     52849 |   __pyx_type_9adios_mpi_smartdict.tp_print = 0;
     60           |                                   ^~~~~~~~
  >> 61     adios_mpi.cpp:52854:32: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member n
            amed 'tp_print'
     62     52854 |   __pyx_type_9adios_mpi_writer.tp_print = 0;
     63           |                                ^~~~~~~~
  >> 64     adios_mpi.cpp:52859:34: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member n
            amed 'tp_print'
     65     52859 |   __pyx_type_9adios_mpi_attrinfo.tp_print = 0;
     66           |                                  ^~~~~~~~
  >> 67     adios_mpi.cpp:52864:33: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member n
            amed 'tp_print'
     68     52864 |   __pyx_type_9adios_mpi_varinfo.tp_print = 0;
     69           |                                 ^~~~~~~~
     70     adios_mpi.cpp: In function 'PyObject* __Pyx_decode_c_bytes(const char*, Py_ssize_t, Py_s
            size_t, Py_ssize_t, const char*, const char*, PyObject* (*)(const char*, Py_ssize_t, con
            st char*))':
     71     adios_mpi.cpp:54345:45: warning: 'PyObject* PyUnicode_FromUnicode(const Py_UNICODE*, Py_
            ssize_t)' is deprecated [-Wdeprecated-declarations]
     72     54345 |         return PyUnicode_FromUnicode(NULL, 0);
     73           |                                             ^

     ...

     207    adios_mpi.cpp:54875:59: note: in expansion of macro 'PyUnicode_GET_SIZE'
     208    54875 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key
            )) ? 1 :
     209          |                                                           ^~~~~~~~~~~~~~~~~~
     210    /home/axel/src/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.3.0/python-3.9.9-s776hol
            6xrbzt5key3hfwecl4mowuupv/include/python3.9/cpython/unicodeobject.h:446:26: note: declar
            ed here
     211      446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
     212          |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
  >> 213    error: command '/home/axel/src/spack/lib/spack/env/gcc/g++' failed with exit code 1

See build log for details:
  /tmp/axel/spack-stage/spack-stage-py-adios-1.13.1-a6rwa4ie27dw6mhrg3pkklwhmv3lpiyl/spack-build-out.txt
```

**Comment by ax3l** [comment]
Works, fantastic! Thanks for the hint!

I noticed that the makefile does not reliably re-create the `.cpp` files from the `.pyx` files. In Spack, I had to remove them beforehand and disable `make` parallelism (`-j`) to get it to build: https://github.com/spack/spack/pull/28223

**Comment by Yikun** [comment]
Looks like we still hit this error with suggested commands:
```
[  214s] + make CYTHON=y MPI=y python
[  214s] python setup.py build_ext -lrt
[  214s] running build_ext
[  214s] building 'adios.adios' extension
[  214s] creating build
[  214s] creating build/temp.linux-aarch64-3.9
[  214s] gcc -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -D_GNU_SOURCE -fPIC -fwrapv -D_GNU_SOURCE -fPIC -fwrapv -fstack-protector-strong -D_FORTIFY_SOURCE=2 -O2 -funsigned-char -D_GNU_SOURCE -fPIC -fwrapv -fstack-protector-strong -D_FORTIFY_SOURCE=2 -O2 -funsigned-char -D_GNU_SOURCE -fPIC -fwrapv -fstack-protector-strong -D_FORTIFY_SOURCE=2 -O2 -funsigned-char -I/opt/ohpc/pub/libs/gnu12/numpy/1.19.5/lib64/python3.9/site-packages/numpy/core/include -I/home/abuild/rpmbuild/BUILD/adios-1.13.1/src/public -L/home/abuild/rpmbuild/BUILD/adios-1.13.1/src -I/opt/ohpc/pub/mpi/openmpi4-gnu12/4.1.4/include -fPIC -D_NOMPI -I/opt/ohpc/pub/libs/gnu12/numpy/1.19.5/lib64/python3.9/site-packages/numpy/core/include -I/opt/ohpc/pub/libs/gnu12/openmpi4/adios/1.13.1/include -I/opt/ohpc/pub/libs/gnu12/openmpi4/netcdf/4.9.0/include -I/opt/ohpc/pub/libs/gnu12/openmpi4/hdf5/1.10.8/include -I/usr/include -I/usr/include/python3.9 -c adios.cpp -o build/temp.linux-aarch64-3.9/adios.o -Wno-uninitialized -Wno-unused-function
[  214s] In file included from /opt/ohpc/pub/libs/gnu12/numpy/1.19.5/lib64/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822,
[  214s]                  from /opt/ohpc/pub/libs/gnu12/numpy/1.19.5/lib64/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
[  214s]                  from /opt/ohpc/pub/libs/gnu12/numpy/1.19.5/lib64/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:4,
[  214s]                  from adios.cpp:540:
[  214s] /opt/ohpc/pub/libs/gnu12/numpy/1.19.5/lib64/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
[  214s]    17 | #warning "Using deprecated NumPy API, disable it with " \
[  214s]       |  ^~~~~~~
[  215s] adios.cpp: In function ‘PyObject* PyInit_adios()’:
[  215s] adios.cpp:52250:30: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
[  215s] 52250 |   __pyx_type_5adios_softdict.tp_print = 0;
[  215s]       |                              ^~~~~~~~
[  215s] adios.cpp:52261:26: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
[  215s] 52261 |   __pyx_type_5adios_file.tp_print = 0;
[  215s]       |                          ^~~~~~~~
[  215s] adios.cpp:52287:31: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
[  215s] 52287 |   __pyx_type_5adios_blockinfo.tp_print = 0;
[  215s]       |                               ^~~~~~~~
[  215s] adios.cpp:52300:25: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
[  215s] 52300 |   __pyx_type_5adios_var.tp_print = 0;
[  215s]       |                         ^~~~~~~~
[  215s] adios.cpp:52306:26: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
[  215s] 52306 |   __pyx_type_5adios_attr.tp_print = 0;
[  215s]       |                          ^~~~~~~~
[  215s] adios.cpp:52312:27: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
[  215s] 52312 |   __pyx_type_5adios_group.tp_print = 0;
[  215s]       |                           ^~~~~~~~
[  215s] adios.cpp:52338:31: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
[  215s] 52338 |   __pyx_type_5adios_smartdict.tp_print = 0;
[  215s]       |                               ^~~~~~~~
[  215s] adios.cpp:52343:28: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
[  215s] 52343 |   __pyx_type_5adios_writer.tp_print = 0;
[  215s]       |                            ^~~~~~~~
[  215s] adios.cpp:52348:30: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
[  215s] 52348 |   __pyx_type_5adios_attrinfo.tp_print = 0;
[  215s]       |                              ^~~~~~~~
[  215s] adios.cpp:52353:29: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
[  215s] 52353 |   __pyx_type_5adios_varinfo.tp_print = 0;
[  215s]       |                             ^~~~~~~~
```



[1] https://build.openeuler.org/package/live_build_log/home:huangtianhua:ohpc/adios-gnu12-openmpi4/standard_aarch64/aarch64

**Comment by martin-g** [comment]
Trying to build ADIOS 1.13.1 (latest release, from Apr 18 2018) fails with the above problem.
adios.cpp and adios_mpi.cpp are regenerated with Cython 0.29 at Oct 2 2019 with https://github.com/ornladios/ADIOS/commit/327e15919ce7369d556f6bb0d3b79af9066aed39
I think it is time for a new release!

**Comment by jychoi-hpc** [comment]
It looks like the cython version 0.29 at Oct 2 2019 looks old. I just tried adios 1.13.1, cython 0.29.32, and python 3.9.13 and it works for me:
```
$ make CYTHON=y MPI=y python
cython --cplus adios_mpi.pyx
/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /gpfs/alpine/csc143/world-shared/jyc/summit/src/adios_develop/wrappers/numpy/adios_mpi.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
cython --cplus adios.pyx
/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /gpfs/alpine/csc143/world-shared/jyc/summit/src/adios_develop/wrappers/numpy/adios.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
python setup.py build_ext -lrt
/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
running build_ext
building 'adios.adios' extension
gcc -pthread -B /gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -mcpu=power8 -fPIC -O2 -isystem /gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/include -I/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/include -mcpu=power8 -fPIC -O2 -isystem /gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/include -fPIC -D_NOMPI -I/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/numpy/core/include -I/gpfs/alpine/world-shared/csc143/jyc/summit/sw/adios/v1.13.1/gcc9.1.0/include -I/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/include/python3.9 -c adios.cpp -o build/temp.linux-ppc64le-cpython-39/adios.o -Wno-uninitialized -Wno-unused-function
In file included from /gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969,
                 from /gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from adios.cpp:761:
/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
g++ -pthread -B /gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/compiler_compat -shared -Wl,-rpath,/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib -Wl,-rpath-link,/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib -L/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib -L/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib -Wl,-rpath,/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib -Wl,-rpath-link,/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib -L/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib build/temp.linux-ppc64le-cpython-39/adios.o -L/gpfs/alpine/world-shared/csc143/jyc/summit/sw/adios/v1.13.1/gcc9.1.0/lib -ladios_nompi -lrt -lm -lrt -o build/lib.linux-ppc64le-cpython-39/adios/adios.cpython-39-powerpc64le-linux-gnu.so
python setup_mpi.py build
/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
running build
running build_src
running build_py
copying src_mpi/__init__.py -> build/lib.linux-ppc64le-cpython-39/adios_mpi
running build_ext
MPI configuration: [mpi] from 'mpi.cfg'
MPI C compiler:    /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.1.0/spectrum-mpi-10.4.0.3-20210112-6jbupg3thjwhsabgevk6xmwhd2bbyxdc/bin/mpicc
MPI C++ compiler:  /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.1.0/spectrum-mpi-10.4.0.3-20210112-6jbupg3thjwhsabgevk6xmwhd2bbyxdc/bin/mpicxx
MPI F77 compiler:  /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.1.0/spectrum-mpi-10.4.0.3-20210112-6jbupg3thjwhsabgevk6xmwhd2bbyxdc/bin/mpif77
MPI F90 compiler:  /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.1.0/spectrum-mpi-10.4.0.3-20210112-6jbupg3thjwhsabgevk6xmwhd2bbyxdc/bin/mpif90
building 'adios_mpi.adios_mpi' extension
/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.1.0/spectrum-mpi-10.4.0.3-20210112-6jbupg3thjwhsabgevk6xmwhd2bbyxdc/bin/mpicc -B /gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/compiler_compat -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -I/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/numpy/core/include -I/gpfs/alpine/world-shared/csc143/jyc/summit/sw/adios/v1.13.1/gcc9.1.0/include -I/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/include/python3.9 -c adios_mpi.cpp -o build/temp.linux-ppc64le-cpython-39/adios_mpi.o -Wno-unused-function -Wno-uninitialized
In file included from /gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969,
                 from /gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from adios_mpi.cpp:762:
/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib/python3.9/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.1.0/spectrum-mpi-10.4.0.3-20210112-6jbupg3thjwhsabgevk6xmwhd2bbyxdc/bin/mpicxx -B /gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/compiler_compat -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -Wall -B /gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/compiler_compat -shared -Wl,-rpath,/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib -Wl,-rpath-link,/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib -L/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib -L/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib -Wl,-rpath,/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib -Wl,-rpath-link,/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib -L/gpfs/alpine/world-shared/csc143/jyc/summit/sw/anaconda3/2022.10/lib build/temp.linux-ppc64le-cpython-39/adios_mpi.o -L/gpfs/alpine/world-shared/csc143/jyc/summit/sw/adios/v1.13.1/gcc9.1.0/lib -ladios -lrt -lm -o build/lib.linux-ppc64le-cpython-39/adios_mpi/adios_mpi.cpython-39-powerpc64le-linux-gnu.so
```
(removed some warnings)

I don't know which version of cython starts supproting python 3.9. But, can you try with different cython versions?

**Comment by martin-g** [comment]
I wonder how this works for you with v1.13.1!
https://raw.githubusercontent.com/ornladios/ADIOS/v1.13.1/wrappers/numpy/adios.cpp does not use checks like `#if PY_VERSION_HEX < 0x030800B1` before trying to access `.tp_print` as it does in [master](https://raw.githubusercontent.com/ornladios/ADIOS/master/wrappers/numpy/adios.cpp)

I'll try to investigate some more tomorrow!

**Comment by ax3l** [comment]
@martin-g @Yikun you are probably aware (and don't let me break our enthusiasm), but ADIOS1 is now deprecated and ADIOS2 is the new hot project: https://github.com/ornladios/ADIOS2

**Comment by jychoi-hpc** [comment]
I used the following command to re-generate `adios.cpp` and `adios_mpi.cpp`:
```
make CYTHON=y MPI=y python
```
As @ax3l said, I also recommend to use Adios2 if possible.

**Comment by williamfgc** [comment]
> If we face other issues most probably we will move to ADIOS 2!

ADIOS2 also has more features that have been maintained for a few years.
