### ISSUE TITLE
error: non-floating-point argument in call to function '__builtin_is*'

### ISSUE THREAD

**Issue by chapouvalpin** [ornladios/ADIOS#63]
ADIOS 1.8.0 or 1.9.0 fail to build with gcc 5.3.0. I have got the following error:

```
core/adios_internals.c: In function 'adios_generate_var_characteristics_v1':
core/adios_internals.c:4754:28: error: non-floating-point argument in call to function '__builtin_isnan'
             hist = (struct adios_hist_struct *) stats[map[adios_statistic_hist]].data; \
                            ^
core/adios_internals.c:4809:13: note: in expansion of macro 'ADIOS_STATISTICS'
             ADIOS_STATISTICS(int8_t,1)
             ^
core/adios_internals.c:4754:28: error: non-floating-point argument in call to function '__builtin_isfinite'
             hist = (struct adios_hist_struct *) stats[map[adios_statistic_hist]].data; \
                            ^
[...]
make: *** [all] Error 2
```

**Comment by chapouvalpin** [comment]
I think that the version of gcc is not relevant. The bug appears when I compile under my Arch Linux machine. With my Gentoo machine, ADIOS compiles with no error. The gcc version is the same (5.3.0). However, the glibc version differs. On Arch Linux, the version of glibc is 2.23 and on Gentoo it is 2.22.

**Comment by Jorispilot** [comment]
Got the same error message.

I use archlinux version 4.4.5-1-ARCH on a x86_64 architecture. I have glibc v2.23,gcc 5.3.0 and ADIOS 1.8.0.

**Comment by pnorbert** [comment]
Hi, can you please try to build the master branch with this compiler/glibc combo? I fixed this issue there based on https://github.com/torch/torch7/issues/355

**Comment by chapouvalpin** [comment]
Hi, I confirm that the problem is fixed in the master branch. Thank you!

Now I have this error when I compile with hdf5. Without hdf5 support there is no error.

```
/usr/include/mpi.h:324:30: erreur : conflicting types for ‘MPI_Offset’
 typedef OMPI_MPI_OFFSET_TYPE MPI_Offset;
                              ^
In file included from ../../src/public/adios_mpi.h:13:0,
                 from ../../src/public/adios_read_v1.h:19,
                 from ../../src/public/adios_read.h:15,
                 from bp2h5.c:36:
../../src/public/mpidummy.h:29:18: note : previous declaration of ‘MPI_Offset’ was here
 typedef uint64_t MPI_Offset;
                  ^
```

**Comment by pnorbert** [comment]
Please use
   export CC=gcc
   export MPICC=mpicc
before configuring adios

If you get this error when building bp2h5, then this is an error due to
trying to build it with parallel hdf5. Use --without-hdf5
--with-phdf5=<your parallel hdf5 install directory>

**Comment by chapouvalpin** [comment]
> Please use export CC=gcc export MPICC=mpicc before configuring adios If you get this error when building bp2h5, then this is an error due to trying to build it with parallel hdf5. Use --without-hdf5 --with-phdf5=<your parallel hdf5 install directory>

Thank you! I forgot I just installed the parallel version of hdf5.
